### ISSUE TITLE
use keyring instead of getOption for creds

### ISSUE THREAD

**Issue by mcnamx** [Metropolitan-Council/councilR#74]
I suggest moving councilR functions over to using `keyring` package for storing credentials as a more secure option than the `getOption()` in current usage, to set one best practices standard across Council repos/packages

**Comment by eroten** [comment]
As is noted in [Posit documentation](https://solutions.posit.co/connections/db/best-practices/managing-credentials/), using `{keyring}` is preferred over using `getOption()`. For this change we will need to 
- Update Options vignette
- update all functions to use keyring instead of getOption()
- communicate to all councilR users that they must update their machines to the new credential storage
